apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- constraints/banish-use-namespace-default-constraint.yaml
- constraints/no-root-containers-constraint.yaml
- templates/banish-use-namespace-default-template.yaml
- templates/no-root-containers-template.yaml
