apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- constraints/hostpath-volume-constraint.yaml
- constraints/no-root-containers-constraint.yaml
- templates/hostpath-volume-template.yaml
- templates/no-root-containers-template.yaml
