apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- templates/banish-pod-run-roo-template.yaml
- templates/deny-namespace-default-template.yaml
- templates/no-root-containers-template.yaml
- constraints/banish-pod-run-roo-constraint.yaml
- constraints/deny-namespace-default-constraint.yaml
- constraints/no-root-containers-constraint.yaml
