apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- templates/no-root-containers-template.yaml
- templates/require-resource-template.yaml
- templates/restrict-capabilities-template.yaml
- constraints/no-root-containers-constraint.yaml
- constraints/require-resource-constraint.yaml
- constraints/restrict-capabilities-constraint.yaml
