apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- templates/banish-namespace-default-template.yaml
- templates/no-hostpath-volume-template.yaml
- templates/no-root-containers-template.yaml
- templates/require-resource-template.yaml
- constraints/banish-namespace-default-constraint.yaml
- constraints/no-hostpath-volume-constraint.yaml
- constraints/no-root-containers-constraint.yaml
- constraints/require-resource-constraint.yaml
