apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- templates/no-hostports-template.yaml
- templates/no-root-containers-template.yaml
- constraints/no-hostports-constraint.yaml
- constraints/no-root-containers-constraint.yaml
