apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- constraints/cis-resources-constraint.yaml
- templates/cis-resources-template.yaml
- constraints/cis-required-annotations-constraint.yaml
- templates/cis-required-annotations-template.yaml
